#!/bin/sh
csv_prop(){
	echo -ne "$1="
	cat | paste -sd,
}

gen(){
	cat <<-EOF
	## THIS FILE IS AUTOGENERATED
	## edit .sonarcloud_gen.sh instead
	sonar.projectKey=openlgtv_epk2extract
	sonar.organization=openlgtv

	EOF

	(cat <<-EOF
	r1
	EOF
	) | csv_prop "sonar.issue.ignore.multicriteria"

	echo ""

	cat <<-EOF
	# format string is not a string literal
	sonar.issue.ignore.multicriteria.r1.rulekey=c:S5281
	sonar.issue.ignore.multicriteria.r1.resourceKey=**
	EOF

	echo ""

	(cat <<-EOF
	src/*.c
	src/lzhs/*.c
	src/stream/*.c
	src/tools/*.c
	include/*.h
	include/lzhs/*.h
	include/realtek/*.h
	include/stream/*.h
	EOF
	) | csv_prop "sonar.inclusions"

}

cd "$(dirname "$(readlink -f "$0")")"
gen > sonar-project.properties
